#!/usr/bin/env bash
# NOTE: written for bash 3.2 (macOS default) — no associative arrays.
# One-time: build per-environment SOPS keying for this repo's Terraform secrets.
#
# Secrets are encrypted with age (not AWS KMS), so you can create and edit them
# before any AWS account exists. The carlpett/sops Terraform provider reads them at
# plan/apply time via SOPS_AGE_KEY_FILE (see the terraform-scripts wrappers).
#
# WHAT IT DOES (idempotent — safe to re-run):
#   1. Generates a dedicated CI age key per environment, if not already present, into
#      ~/.config/sops/age/<project>-<env>.txt (NOT in the repo).
#   2. Rewrites .sops.yaml with ONE creation rule per environment, each listing YOUR
#      personal key + that environment's CI public key.
#   3. Creates any missing <module>/vars/<workspace>-secrets.json from the committed
#      .example templates (generating strong random values), then encrypts each to its
#      environment's rule. Existing files are re-wrapped (`sops updatekeys`) so they gain
#      new recipients without changing their contents.
#   4. Writes the CI PRIVATE keys to ci-age-keys.OUTPUT.txt (gitignored), then DELETE it.
#      As shipped nothing in CI decrypts secrets (terraform does it locally, and the deploy
#      workflow only builds + rolls the service) — these keys are for when you add a workflow
#      that runs terraform itself. See SECRETS.md "Do you need the CI keys?".
#
# Your personal key stays a recipient on every file, so you can always `sops -d` locally.
#
# Usage:  ./setup-sops.sh [project-name]      (default: the workspace prefix, e.g. myapp)
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$REPO_ROOT"

PROJECT="${1:-myapp}"
AGE_DIR="$HOME/.config/sops/age"
PERSONAL_KEY_FILE="${SOPS_AGE_KEY_FILE:-$AGE_DIR/keys.txt}"
ENVS=(dev prod)
OUT="$REPO_ROOT/ci-age-keys.OUTPUT.txt"

# Modules whose vars/ hold SOPS secrets. Keep in sync with the `data "sops_file"`
# blocks (currently ecs/main.tf and rds/main.tf).
MODULES=(ecs rds)

command -v sops >/dev/null || { echo "sops not installed — brew install sops"; exit 1; }
command -v age-keygen >/dev/null || { echo "age-keygen not installed — brew install age"; exit 1; }

# --- 0. personal key ----------------------------------------------------------
mkdir -p "$AGE_DIR"
if [ ! -f "$PERSONAL_KEY_FILE" ]; then
  echo "No personal age key at $PERSONAL_KEY_FILE — generating one."
  age-keygen -o "$PERSONAL_KEY_FILE" 2>/dev/null
  chmod 600 "$PERSONAL_KEY_FILE"
fi

PERSONAL_PUB="$(grep 'public key:' "$PERSONAL_KEY_FILE" | sed 's/.*public key: //')"
[ -n "$PERSONAL_PUB" ] || { echo "Could not read a public key from $PERSONAL_KEY_FILE"; exit 1; }
echo "Personal recipient: $PERSONAL_PUB"

# --- 1. per-env CI keys -------------------------------------------------------
# bash 3.2: no assoc arrays. Derive the CI key file + pubkey from $env on demand.
ci_key_file() { echo "$AGE_DIR/$PROJECT-$1.txt"; }
ci_pub()      { grep 'public key:' "$(ci_key_file "$1")" | sed 's/.*public key: //'; }

for env in "${ENVS[@]}"; do
  kf="$(ci_key_file "$env")"
  if [ ! -f "$kf" ]; then
    echo "Generating CI key for $env -> $kf"
    age-keygen -o "$kf" 2>/dev/null
    chmod 600 "$kf"
  else
    echo "CI key for $env already exists ($kf)"
  fi
done

# --- 2. rewrite .sops.yaml with one rule per env ------------------------------
echo "Rewriting .sops.yaml ..."
{
  cat <<'HEADER'
# SOPS encryption rules — ONE creation rule per environment (per-env keying).
#
# GENERATED by ./setup-sops.sh — re-run that script to add environments or recipients
# rather than hand-editing, so the secrets files get re-wrapped to match.
#
# Each <module>/vars/<workspace>-secrets.json is decryptable by the operator's personal
# key AND that environment's dedicated CI key (whose PRIVATE half is the SOPS_AGE_KEY
# GitHub-environment secret). A leaked dev CI key cannot decrypt prod. To rotate a
# compromised env key: regenerate it, re-run setup-sops.sh, then update the GitHub secret.
#
# Onboarding a teammate: add their age PUBLIC key to every rule's `age:` list, then
# `sops updatekeys <module>/vars/<workspace>-secrets.json` for each file to re-wrap it.
#
# age public keys are NOT secret — committing them is expected and safe.
creation_rules:
HEADER
  for env in "${ENVS[@]}"; do
    cat <<RULE
  - path_regex: vars/.*-$env-secrets\\.json\$
    age: >-
      ${PERSONAL_PUB},$(ci_pub "$env")
RULE
  done
} > .sops.yaml

# --- 3. create missing secret files from the .example templates, encrypt/rewrap ---
# Generated values are strong randoms; edit later with `sops <file>`.
rand() { openssl rand -hex 32; }

for module in "${MODULES[@]}"; do
  for env in "${ENVS[@]}"; do
    f="$module/vars/$PROJECT-$env-secrets.json"
    example="$module/vars/$PROJECT-$env-secrets.json.example"

    if [ -f "$f" ]; then
      echo "Re-wrapping existing $f for its recipients ..."
      SOPS_AGE_KEY_FILE="$PERSONAL_KEY_FILE" sops updatekeys --yes "$f"
      continue
    fi

    # Fall back to the shipped myapp-* template when running before the myapp find/replace,
    # or with a project name that has no template of its own.
    if [ ! -f "$example" ]; then
      example="$module/vars/myapp-$env-secrets.json.example"
    fi
    [ -f "$example" ] || { echo "No template for $f (looked for $module/vars/{$PROJECT,myapp}-$env-secrets.json.example) — skipping"; continue; }

    echo "Creating $f from $example (random values) ..."
    # Replace every "replace-with-..." placeholder value with a fresh random.
    sed -E "s/\"replace-with-[^\"]*\"/\"$(rand)\"/" "$example" > "$f"
    SOPS_AGE_KEY_FILE="$PERSONAL_KEY_FILE" sops --encrypt --in-place "$f"
  done
done

# --- 4. emit CI private keys for GitHub (gitignored) --------------------------
{
  echo "# CI age PRIVATE keys — paste each into the matching GitHub environment's"
  echo "# SOPS_AGE_KEY secret (Settings > Environments > <env> > Environment secrets)."
  echo "# Then DELETE this file. Do NOT commit it."
  echo
  for env in "${ENVS[@]}"; do
    echo "===== GitHub environment: $env  (SOPS_AGE_KEY) ====="
    grep 'AGE-SECRET-KEY' "$(ci_key_file "$env")"
    echo
  done
} > "$OUT"
chmod 600 "$OUT"

echo
echo "DONE."
echo
echo "Verify the per-env split before relying on it — the dev key must FAIL on prod:"
echo "  SOPS_AGE_KEY_FILE=$(ci_key_file dev) sops -d ${MODULES[0]}/vars/$PROJECT-prod-secrets.json"
echo
echo "CI private keys: $OUT"
echo "You likely do NOT need them yet (nothing in CI decrypts secrets as shipped) —"
echo "see SECRETS.md. Either way, DELETE that file when you're done with it."
